### ISSUE TITLE
Clicking "Top" and then "Recent"

### ISSUE THREAD

**Issue by olback** [tahnik/devRantron#122]
Clicking "Top" and then "Recent" quickly results in top rants showing but the buttons on the top indicates "Recent".
![devrantron_2017-07-30_02-40-41](https://user-images.githubusercontent.com/8039145/28749693-aaa73216-74d0-11e7-807c-a48163f4cb38.png)

**Comment by hex2f** [comment]
Were currently working on this, check #104. Should be fixed tomorrow.

**Comment by olback** [comment]
👍

**Comment by tahnik** [comment]
This is actually a bit different than #104. Need to have a look.

**Comment by hex2f** [comment]
This seems to be the network requests arriving at different times. @tahnik, suggestion for fix: don't dispatch send event unless last one is finished.
