### ISSUE TITLE
Clickable tags

### ISSUE THREAD

**Issue by nblackburn** [tahnik/devRantron#126]
At the moment tags are not clickable, it would be good to have them list rants with those tags.

**Comment by DRSDavidSoft** [comment]
This will first need #116 to work. Then it can be implemented.
@tahnik Also, clicking on the comments icon should open the comments page

**Comment by nblackburn** [comment]
@DRSDavidSoft Good idea, might be an idea to make a separate issue for that though, it makes tracking these way easier.

**Comment by DRSDavidSoft** [comment]
@nblackburn You're right, #137 seems to fix the clicking on comments icon issue.
I might work on #116 to make clickable tags working, though I first should study RantScript by @RekkyRek.
