### ISSUE TITLE
devRantron site

### ISSUE THREAD

**Issue by olback** [tahnik/devRantron#127]
First of, is this the right place for issues related to devrantron.firebaseapp.com?

Anyway, here is some feedback!
1. Make the site "hero" part more responsive.
2. The Linux download button downloads a .deb package, isn't those for debian-based operating systems only? (Might be totally wrong).

Also, a catchy domain name wouldn't hurt. If you're interested i could contribute with that. Contact me on [Twitter](https://twitter.com/mrolback) or on my [website](https://olback.net#contact).

**Comment by tahnik** [comment]
@Dacexi

**Comment by hex2f** [comment]
1. Absolutely!
2. That's true. I guess i'll add another button for .AppImage

I was going to buy a domain but forgot until like 1h before launch. Will come soon.

**Comment by DRSDavidSoft** [comment]
@RekkyRek DevRantron.io?

**Comment by hex2f** [comment]
@DRSDavidSoft unfortunately not an io domain (they are like 50 bux) prob a .com

**Comment by DRSDavidSoft** [comment]
@RekkyRek DevRantron.ir? It's cheap and it looks cool

**Comment by tahnik** [comment]
I will close it for now. Please open the issue at https://github.com/RekkyRek/devRantronWeb/issues
