### ISSUE TITLE
Trouble closing app

### ISSUE THREAD

**Issue by DFoxinator** [tahnik/devRantron#131]
When I tried to close the app, it seemed to not shutdown correctly and got stuck. I'm using it on Mac OS 10.12.5. I had to go to activity monitor and kill the main devRantron process in order to get it to shutdown.

**Comment by tahnik** [comment]
Unusual. Although we haven't done much testing on Mac as I don't have one. Would be good to know if it's happening every time?

**Comment by tahnik** [comment]
What the hell! @Dacexi why is the tray icon in mac so big?
