### ISSUE TITLE
Debugging: some issues, solutions and ideas

### ISSUE THREAD

**Issue by salmansamie** [tahnik/devRantron#135]
[debugging devrantron.zip](https://github.com/tahnik/devRantron/files/1192095/debugging.devrantron.zip)

**Comment by hex2f** [comment]
You only need to run "npm run dev" as it runs the other two commands.
As for multithreading; To my knowledge node does not have very good multithread support yet.

Maybe @tahnik has some more input on this as i'm just the UI guy.

**Comment by tahnik** [comment]
Thanks man @Dacexi He is one of my closest friends. I asked him for this :)
