### ISSUE TITLE
Bunch of bugs

### ISSUE THREAD

**Issue by kovaacs** [tahnik/devRantron#145]
- It doesn't make sense to be able to subscribe to yourself
- When you do, there's a typo: "Sub[sri]bed to user"
- When an URL gets shortened, clicking on it will open the shortened URL in the browser, resulting in a 404: e.g. theverge.com/2015/8... will open theverge.com/2015/8

**Comment by kovaacs** [comment]
I fixed the typo here: https://github.com/tahnik/devRantron/pull/147

**Comment by tahnik** [comment]
@kovaacs great thanks!

**Comment by tahnik** [comment]
@kovaacs Looks like URL shortening is more of a devrant problem then of devrantron. Will not be able to fix that. Sorry :(
