### ISSUE TITLE
Add brew cask installation instructions

### ISSUE THREAD

**Issue by sepehr** [tahnik/devRantron#150]
devRantron has just [got a cask](https://github.com/caskroom/homebrew-cask/pull/37405) and is installable with a `brew cask install devrantron` on macOS machines. 

You might want to update installation instructions to reflect that. I wasn't sure which part of the readme file to update as it's a crossplatform app.

**Comment by tahnik** [comment]
@sepehr Thank you! can you please confirm that auto launch during startup works when installed via brew cask?

**Comment by sepehr** [comment]
Yes, it does. In fact, it has nothing to do with the way brew installs casks. 

That cask formula there just mimics the user installation by moving the app to the corresponding application directory. However, upon uninstallation, it quits the app, drops the login item and trashes the leftover directories.

**Comment by tahnik** [comment]
@sepehr I had some issues with auto-start when I tried to upload the .deb version in Ubuntu's launchpad. But great to know it works! I will add it on the website https://devrantron.firebaseapp.com soon.
