### ISSUE TITLE
Total number of ++'s not correct on different pages

### ISSUE THREAD

**Issue by XiovV** [tahnik/devRantron#154]
On the main page
![devrant1](https://user-images.githubusercontent.com/20326947/29017792-b5928dc2-7b58-11e7-8d63-4e8f745cb13c.PNG)

On my profile page
![devrant2](https://user-images.githubusercontent.com/20326947/29017821-d4751a8e-7b58-11e7-995e-6c1b62981af9.PNG)

**Comment by tahnik** [comment]
That is pretty weird. Because we update the score every time you receive a new notification. Need to have a look. Thanks.
