### ISSUE TITLE
Bug when opening links

### ISSUE THREAD

**Issue by TheWeirdDev** [tahnik/devRantron#156]
![screenshot from 2017-08-07 14-43-01](https://user-images.githubusercontent.com/6321734/29022613-4dc7e152-7b7f-11e7-9815-0a099e3c7e8b.png)

For example, when i click on this link, it opens `play.google.com/store/apps` instead of the whole url.

**Comment by tahnik** [comment]
Again, I think it's a devrant limitation. I think devrant doesn't store the full URL.

**Comment by TheWeirdDev** [comment]
But it opens the correct url in official app.

**Comment by tahnik** [comment]
Right, I'll have a look. Thanks
