### ISSUE TITLE
Devrantron Website No Title

### ISSUE THREAD

**Issue by KylePiira** [tahnik/devRantron#162]
The [Devrantron website](https://devrantron.firebaseapp.com/) has two title tags causing the browser to display the URL as the title.
![image](https://user-images.githubusercontent.com/17210104/29251922-f9b6c072-802b-11e7-86b6-151ccddd2e50.png)

**Comment by nblackburn** [comment]
https://github.com/RekkyRek/devRantronWeb/pull/2

**Comment by tahnik** [comment]
Thanks @nblackburn I will close the issue here
