### ISSUE TITLE
Notifs not an open on menu

### ISSUE THREAD

**Issue by taylorviktorya** [tahnik/devRantron#169]
![devrantronscreenshot](https://user-images.githubusercontent.com/31082048/29388048-df581e10-8297-11e7-9843-514cc455979b.PNG)

I only had the application for a few hours before my computer died last time but i remember there being an option for notifs on the application. They don't seem to be there now... Not sure if i'm doing something wrong or what happened. I hope you're ok with the screenshot, I was struggling to explain what I was (not) seeing.

If it helps, I'm running fully updated Windows 10 Pro

**Comment by hex2f** [comment]
Pretty sure we've never had notifs in sidebar. They are up in the bubble at top right of the window :)

(There are settings for notifs in the settings tab if that's what you're thinking about)

**Comment by taylorviktorya** [comment]
I Hadn't seen that, either, but I'll look again
