### ISSUE TITLE
Expanded collab functionality

### ISSUE THREAD

**Issue by nblackburn** [tahnik/devRantron#178]
Add the ability to create, edit and delete collabs.

- [ ] Create a collab
- [ ] Edit a collab
- [ ] Delete a collab

**Comment by tahnik** [comment]
#119

**Comment by hex2f** [comment]
wouldn't this be quite hard to do since you can't purchase collabs from pc?

**Comment by nblackburn** [comment]
@RekkyRek That is a fair point, you can do the second two though.

**Comment by tahnik** [comment]
@nblackburn doing the second probably not gonna be worth it if we don't add the add collab functionality. I hope you understand that from the programming point of view. I will still keep it open and will consider it when I add the edit functionality.

**Comment by nblackburn** [comment]
@tahnik Makes sense, i understand it doesn't make a great deal of sense only half doing it.
