### ISSUE TITLE
Avatar builder

### ISSUE THREAD

**Issue by nblackburn** [tahnik/devRantron#179]
Implement the ability to edit your avatar from within the application.

**Comment by tahnik** [comment]
It might be easier to redirect them to the web app. As far as I know, the avatar builder in Web App is built with React. Need to investigate.

**Comment by nblackburn** [comment]
@tahnik It is built with React but it would be nice to have it in the application, i know the endpoints if it helps at all.

**Comment by hex2f** [comment]
@nblackburn this would be a bit of a bigger project as the avatar builder is quite complicated, although not out of reach.
