### ISSUE TITLE
Seperate out settings

### ISSUE THREAD

**Issue by nblackburn** [tahnik/devRantron#180]
At the moment general settings is a mash of different things, it would make sense to split them out into tabs for each area that the setting deals with.

- Notifications
- Filters

That way the general settings remains general.

**Comment by tahnik** [comment]
They are separated with indentation. Tabs might be an enhancement. Will look into it later.

btw @nblackburn, I am on a holiday and will fix these things once I am back. Thanks for opening these issues :)
