### ISSUE TITLE
Unable to change the window height and width

### ISSUE THREAD

**Issue by tracktraps** [tahnik/devRantron#181]
OS: 4.12.8-2-ARCH
Changing the window height and width is only possible after closing the main window and clicking on the tray icon "Open Notifications".

**Comment by tahnik** [comment]
@RekkyRek do you still have arch? Are you having this problem at all?

**Comment by tracktraps** [comment]
I also tried it with Ubuntu 16.04. Same problem. I can change (sometimes) the width but not the height of the window. It only works after closing the main window and clicking on the tray icon "Open Notifications".

**Comment by hex2f** [comment]
I'll look into this as soon as I get home.

**Comment by hex2f** [comment]
Very odd. I could not replicate this issue on KDE Neon. Will look into it though.

**Comment by hex2f** [comment]
I've been doing some more testing and been using devRantron heavily the last week on 3 different OS's (KDE Neon, Ubuntu, Windows) and i was not able to replicate it. Therefore i'm closing it. Feel free to reopen if you find a good way to replicate it.
