### ISSUE TITLE
Confirmation dialog when deleting a rant or comment

### ISSUE THREAD

**Issue by tahnik** [tahnik/devRantron#183]

**Comment by ewan-laws** [comment]
What is worse the icon in commends is a "..." which implies a sort of menu, I clicked on it to edit the comment, and it just deleted it!

**Comment by hex2f** [comment]
@Hedgepig yeah we realised that was an issue quite early. In the current dev build we have a confirmation dialogue when deleting anything but I was thinking of making it click to open instead of hover to open.
