### ISSUE TITLE
Portable edition or command line parameters to change installation destination

### ISSUE THREAD

**Issue by r15ch13** [tahnik/devRantron#188]
Hi, would it be possible to add a portable version?
I'd love to add devRantron to the [extras bucket](https://github.com/lukesampson/scoop-extras) of [scoop](https://github.com/lukesampson/scoop) (windows cli installer). 😄 
The setup only installs to `%appdata%` and I can't find any command line parameters to change this behavior 😞

**Comment by hex2f** [comment]
You should be able to just copy the programs folder to usb stick and run the exe

**Comment by r15ch13** [comment]
Scoop uses JSON files to describe how to download and extract a program (See [nodejs](https://github.com/lukesampson/scoop/blob/master/bucket/nodejs.json) for example). Programs get installed to `%USERPROFILE%\scoop\apps\<name>`.
It would be no problem if extracting the setup.exe would result in a complete program folder. But it contains only the uninstaller and the actual program is in another `app-64.7z`. Scoop is currently unable to perform two extractions in a row.

**Comment by r15ch13** [comment]
Okay uses a pre install script to extract it anyway: https://github.com/lukesampson/scoop-extras/commit/9e9c080ca175aff066bd7ec9d508adef12d8313f
