### ISSUE TITLE
Emoji parser need to be fixed

### ISSUE THREAD

**Issue by ShellAddicted** [tahnik/devRantron#192]
I posted a rant that contains a copy->paste of git log

the emoji parser made this:
Date:   Sat Sep 9 00:28:00 2017

to this:
Date:   Sat Sep 9 00undefined00 2017

Bug found on Linux v1.3.6.

**Comment by hex2f** [comment]
Ah, this should be simple to fix. Just if parsedEmoji == undefined then ignore. Will include in the next bugfix :+1:
