### ISSUE TITLE
Rant types

### ISSUE THREAD

**Issue by DFoxinator** [tahnik/devRantron#200]
It would be cool to have the new post type options. In about a month or so, filtering on post types will be available so it's important that rants get classified correctly.

The parameter is "type"

The ids are as follows:
rant = 1
collab = 2 (can just leave out since you probably don't want to implement - would require special params, but they all are free now)
joke/meme = 3
question = 4
devrant = 5
random = 6

We also give a description of each type in the apps the first time you select each one, which might be helpful for new users.

**Comment by tahnik** [comment]
Thanks @DFoxinator, I will add it in the next release.

**Comment by DFoxinator** [comment]
@tahnik awesome, thanks!

**Comment by hex2f** [comment]
@DFoxinator can you edit rant type after rant is posted?

**Comment by DFoxinator** [comment]
@RekkyRek you cannot

**Comment by hex2f** [comment]
@DFoxinator ok, was just wondering if i needed to add it to the api wrapper.

@tahnik rant type has been added to rantscript https://github.com/RekkyRek/RantScript/commit/1288dfe8ba660f30ccd750c705abf76479a364e9
