### ISSUE TITLE
devRantron window is too big for my laptop screen + can't resize

### ISSUE THREAD

**Issue by olback** [tahnik/devRantron#201]
Well, the title basicly says it all.

OS: Ubuntu 17.04
DE: Budgie
devRantron version: latest.
Screen size: 1366x768.
![screenshot from 2017-09-28 22-19-30](https://user-images.githubusercontent.com/8039145/30988799-c9e89822-a49b-11e7-999d-b047a6c2180b.png)

Suggested fix: Allow the window to have a height of less than 800px.
Edit: I looked into the code and saw that the smallest screen size is 768. This would be fine if there were no borders/docks/taskbar. I would suggest changing this to 600px.

**Comment by hex2f** [comment]
yup will do! Should be fixed in the next update :)
