### ISSUE TITLE
Link to rant from comment popup

### ISSUE THREAD

**Issue by ewan-laws** [tahnik/devRantron#205]
There is a dialogue/notification that opens when someone makes a comment on a rant, I think it's after one clicks on the initial notification.

It's a nice feature to be able to see and reply quickly, but it would be nice to click on a link inside that dialogue to open up the main app to that comment.

**Comment by hex2f** [comment]
that is definitely planned. we're reworking the quick reply for the next big update (along with themes)

**Comment by tahnik** [comment]
You can disable the quick reply in the settings for now.

**Comment by ewan-laws** [comment]
Cheers guys, keep up the good work. Hopefully at some point I will have the time to contribute

**Comment by tahnik** [comment]
Thanks @Hedgepig :) Closing this as it can be toggled in settings.
