### ISSUE TITLE
Unable to login on MacOS

### ISSUE THREAD

**Issue by sebkasanzew** [tahnik/devRantron#206]
My account password contains a "^" (this symbol somehow cannot be typed) and I cannot copy-paste the password from my password manager into the form.

As a result I cannot use the App 😢

**Comment by hex2f** [comment]
Sadly, I don't think this is anything we can fix. Seems like a problem in electron :/

**Comment by tahnik** [comment]
We can add a button that will be used to paste. Will release it in the next update.
