### ISSUE TITLE
AUR installer leads to incorrect file type

### ISSUE THREAD

**Issue by itspacrat** [tahnik/devRantron#207]
When installing via yaourt or pacaur, the terminal reads "installation failed - unrecognized filetype" after downloading "package.deb"

running:
Antergos (Arch x64)
DE:
Xfce4
Installing via:
both terminal/pacaur and pamac aur

**Comment by tahnik** [comment]
@parkcitymedia Unfortunately, the package is not maintained by us. Please download the file from release section :)

**Comment by itspacrat** [comment]
Ah, understood. thank you
