### ISSUE TITLE
Ability to list rants side by side

### ISSUE THREAD

**Issue by LoganS1** [tahnik/devRantron#208]
I would love to be able to see the rants appear in in multiple per row instead of just a single line of rants.. Listing the rants like this 
![image](https://user-images.githubusercontent.com/21230472/31857611-36a51b2a-b6a8-11e7-9fdd-ca09dcef2c28.png)

Maybe is could be responsize too?

**Comment by tahnik** [comment]
We tried that in one of our version previously. It looks easy but it's very hard to implement and is not reliable at all. Sorry about that.

**Comment by LoganS1** [comment]
Ok, thanks for responding
