### ISSUE TITLE
Comment box gets out of focus whenever a new notification comes

### ISSUE THREAD

**Issue by PaddiM8** [tahnik/devRantron#211]
Whenever I'm typing a comment and I get a notification, the comment box go out of focus! It's rather annoying, but should be simple fix I guess?

**Comment by hex2f** [comment]
I guess you're talking about OS notifications, we have no control what so ever over that which kind of sucks :/

**Comment by PaddiM8** [comment]
Well this happens on both Linux and Windows, on linux I don't even get any notifications!

**Comment by tahnik** [comment]
I find this very annoying as well. I will see if there is a fix :(
