### ISSUE TITLE
Material theme and color changing background.

### ISSUE THREAD

**Issue by ghost** [tahnik/devRantron#215]
Depending on which color you chose as the background for your avatar changes the color for the dock and backdrop of the whole application, so if I were to choose Red as my avatar color I would have a soft red hue for the entire app as I scroll through rants.
(Obviously it would be a soft hue, because nobody wants to stare at a bright red screen for more than a few seconds :D)
And a request for the future themes would be a material look compared to the current flat design.
Sorry for putting more shit on the heap :sweat_smile:

**Comment by hex2f** [comment]
We're looking into themes for the next update :)
