### ISSUE TITLE
Scrolling through rants issue.

### ISSUE THREAD

**Issue by ghost** [tahnik/devRantron#216]
When I try to scroll through posts (obviously going down through the rants) sometimes it would jumble up the rants I already went by and basically repeat some of the rants I've seen.
It's annoying going by the same rant 5 times when I want to see new stuff.
Thanks :)

**Comment by hex2f** [comment]
Are you using algo or recent? If algo the its a confirmed issue with devRant. Dfox said that they show random rants from previous algo when it runs out of new rants to show you.

**Comment by tahnik** [comment]
I think I know what he is talking about. The thing is I have not changed anything recently. I wonder if something was changed in the devRant api

**Comment by ghost** [comment]
@RekkyRek was right.
It was just the Algo, sorry for making this a big deal.
