### ISSUE TITLE
Fix prod build

### ISSUE THREAD

**Issue by tahnik** [tahnik/devRantron#22]
Not prioritized right now. Maybe later.

**Comment by mainrs** [comment]
Checklist:
- [ ] properly setup `babel-polyfill` in production
- [ ] check why generators are not working at runtime
- [ ] check why generators aren't uglified/minified
  - [ ] move to `babili` instead of `uglifyjs` (`babili` supports es6 code)

**Comment by tahnik** [comment]
#28
