### ISSUE TITLE
No visual change when clicking "Update"

### ISSUE THREAD

**Issue by TheCyaniteProject** [tahnik/devRantron#220]
This isn't a bug, more of a design flaw.

When an update is available (Windows) clicking the "Update" button seeming does nothing. Leading me to click the button a few times, and then going online to manually download the update before realizing that the Application had updated.

Wouldn't it be really simple to display a message saying "The Application will be updated shortly..." or at least grey out the "Update" button so I know it did something..?

**Comment by tahnik** [comment]
@TheCyaniteProject What OS are you using?

**Comment by TheCyaniteProject** [comment]
Windows 10 - Updated.

**Comment by tahnik** [comment]
@TheCyaniteProject That is quite weird. What version of the app are you using now?

Normally the moment you click the update button, it should immediately close the application and show you the progress bar of installing. Once that is done, it should open the application again.

**Comment by TheCyaniteProject** [comment]
I was only one version behind, and now I'm up-to-date. Though, I have a really slow internet connection - 100-300kb/s

**Comment by tahnik** [comment]
@TheCyaniteProject the speed should not matter as in Windows, it downloads the update in the background and shows you update notification once the app has been downloaded.

I am going to release another update (some bugfixes) today. Let me know if it's correctly this time.

**Comment by TheCyaniteProject** [comment]
Alright, I'll reply here after the update.

**Comment by TheCyaniteProject** [comment]
Seems to be fixed now. Upon clicking "Update", the application stopped responding and closed after a few seconds, and then opened up the updater, and then re-launched once it was finished, as intended.

**Comment by tahnik** [comment]
@TheCyaniteProject Great!
