### ISSUE TITLE
Clicking profile icon to hide profile preview..?

### ISSUE THREAD

**Issue by TheCyaniteProject** [tahnik/devRantron#221]
While I'm here, let me throw a recommendation at you.

Every time I open someone's profile card (preview), whether on purpose or by mistake, I ALWAYS try and click their picture again to close it, before hunting down the tiny little "x" with my sensitive mouse. And I guarantee you I'm not alone here. Honestly, maybe this doesn't make sense to you, but it does to me. This just "feels" like it should be a thing. I've had this habit since I first started using devRantron, and I don't think I'll break it anytime soon.

Think about it. <3

Best regards, Cyanite.

PS: You know, the notifications screen really should close when you interact with anything else... Just saying... ;3

**Comment by hex2f** [comment]
Great suggestion! I'll implement it for the next patch :)

**Comment by TheCyaniteProject** [comment]
Thanks a lot~ I really appreciate it.

**Comment by TheCyaniteProject** [comment]
Is there a way to "Unsubscribe" from a rant..? (Sorry for asking here, didn't want to open a new thread for a simple question, and didn't know where else to ask.)

**Comment by tahnik** [comment]
@TheCyaniteProject Not yet, Please create a new issue if you have time.
