### ISSUE TITLE
Wrong comment time

### ISSUE THREAD

**Issue by PrivateGER** [tahnik/devRantron#223]
![issue](https://user-images.githubusercontent.com/29523614/32385489-a86343b6-c0be-11e7-8473-59b184dcb3b1.PNG)
Some comments have a negative time of posting. This bug appears absolutely randomly.

**Comment by hex2f** [comment]
Are you sure your pc is set to the coreect time?

**Comment by PrivateGER** [comment]
Yup.

**Comment by hex2f** [comment]
Alright then I have no clue. We get the time directly from devRant's API so if there's a problem it's most likely  on their side

**Comment by tahnik** [comment]
@PerhapsSomeone I cannot reproduce this either. We had this sort of issue before and most of the time it has to do with some timing issue in your computer.
