### ISSUE TITLE
Overflow menu appears only in mouse hover

### ISSUE THREAD

**Issue by cozyplanes** [tahnik/devRantron#224]
In touchscreen tablets/laptops, i cant expand the overflow menu

when the menu is clicked, it only gets highlighted, not expanded

**Comment by hex2f** [comment]
Which menu are you referring too? Please send an image so that I understand :)

**Comment by cozyplanes** [comment]
![](https://i.imgur.com/YQ3HKjd.png)

**Comment by cozyplanes** [comment]
red circle

**Comment by tahnik** [comment]
@cozyplanes aha, makes sense. I will fix that in the next update.
