### ISSUE TITLE
Missing Icon on window title and in docks.

### ISSUE THREAD

**Issue by ghost** [tahnik/devRantron#227]
After moving the strange .appimage into my opt directory and launching I am running into this issue.
I also noticed that when I pin DevRantron to my dock (Plank) and open it, it opens as a different application and turns into the gears seen in the image below. Also, If I try top open DevRantron from the icon in my dock the application restarts and remains hidden.

System: Arch Linux (XFCE4 desktop on Antergos)

![screenshot_2017-11-18_13-58-20](https://user-images.githubusercontent.com/15480170/32983814-eef65a74-cc68-11e7-8fc9-abf28f006e9f.png)

Is there a real way to install this application, like download source and make?

**Comment by hex2f** [comment]
I'll look into this. Linux seems very picky with Linux icons. I have the icon on my Arch setup 🤔

**Comment by ghost** [comment]
I would like to add some information that I missed in the first post, the icon does in fact appear in my notification area and applications menu. (Love the icon btw)

If you would like any logs or other information please let me know 🙂

**Comment by mrlinnth** [comment]
Can confirm. Same issue on my xubuntu. Appear on notification area, dock and application menu. However showing the default white and blue window icon on taskbar and title bar.

**Comment by hex2f** [comment]
From my experience simply opening the appimage it asks you if you want to install it. Also, you can get a package manager like dpkg and install it using the .deb

**Comment by mrlinnth** [comment]
Yes, @RekkyRek I installed using GDebi Package Installer.

**Comment by ghost** [comment]
@RekkyRek Unfortunately on a system like Arch, using a package manager like dpkg is rather hard, mostly due in part to dependancies.

I did install dpkg on my arch system but after an hour of trying to fix missing dependancies for Devrantron I kindof just gave up..

And yes, opening the appimage does ask if you want to install it, however, for an appimage it is really just making symlinks and menu entries back to the appimage itself.

**Comment by hex2f** [comment]
@CodyTheFurry yeah I know, I use Arch myself too. I use i3gaps though so I never see the icons. We'll look into it I guess.
