### ISSUE TITLE
devRantron website download for Windows is a BLOCKMAP file

### ISSUE THREAD

**Issue by ALMSTJSON** [tahnik/devRantron#240]
I just tried downloading devRantron after a format, and the website (https://devrantron.firebaseapp.com/) only lists a BLOCKMAP file for Windows. After downloading it, simply changing its extension to *.exe won't work.

So currently, you're not able to install devRantron from the main website.

**Comment by hex2f** [comment]
Thanks for the heads up! We fetch the latest build from GitHub so they must have switched around the order or something.

**Comment by ALMSTJSON** [comment]
@RekkyRek No problem lol

**Comment by ALMSTJSON** [comment]
Thanks guyz
