### ISSUE TITLE
Caching problems

### ISSUE THREAD

**Issue by ebourgess** [tahnik/devRantron#251]
Every two, three days I get an error that there was a problem with Caching and I have to sign out and reload the app.

**Comment by hex2f** [comment]
Next time you get an error message, can you open the console using f12 and paste the output here?

**Comment by ebourgess** [comment]
Of course when it happens again

**Comment by ebourgess** [comment]
The problem is back 
![screenshot from 2018-03-02 10-11-32](https://user-images.githubusercontent.com/19877979/36889351-45048f72-1e02-11e8-9dc6-cc3ae93b2450.png)

**Comment by mainrs** [comment]
I'll try to add source-map-support so we can identify the exact line of code where it is happening. It will take some days though @eBourgess . :)
