### ISSUE TITLE
List Items Vertically Spaced Evenly Within a Flexbox Container

### ISSUE THREAD

**Issue by DamianGerard** [tahnik/devRantron#271]
Alright guys, I'm learning CSS right now, and I'm kind of stumped as to why I can't get it to do what I want it to do. It's probably something extremely simple that I'm overlooking.

I'm wanting to have an unordered list containing sub-lists vertically spaced evenly within a flexbox sidebar container and the sub-list items doing the same between each list item. Everything I've tried so far hasn't had any effect on how the list items are displayed.  [whatsapp web](https://openweb.onl/whatsapp-web/)[ whatsapp plus](https://modplus.pro/whatsapp-plus/)

Any help is appreciated.

**Comment by tahnik** [comment]
Hi there, is it possible to share a screenshot of how it looks right now? You might wanna look at justify-space-between when using align-items in the parent flexbox.

**Comment by hex2f** [comment]
@tahnik it's a spam bot lol
