### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by TheWeirdDev** [tahnik/devRantron#97]
I have already posted these feature requests on devRant but i'm going to post them here as well

* Show tags
* A confirmation for logout 
* Comment 'Reply' button
* Edit/Delete buttons for rants and comments
* Show when the rant or comment is posted/edited
* Posting picture/GIF as a comment
* Emoji button for comments
* Disable vote buttons for user's own rants/comments.
* Zoom on a GIF/picture with mouse click
* Ability to open a link (and open devRant links inside the app)
* Open a user profile by clicking on a @mention
* Search section
* Mute notifications for a rant

I also have an issue with sort by 'Top' that always shows 'All' and 'Day','Week' and 'Month' doesn't work ( They work on stories page but not on rants page)

Thank you for your great job.

**Comment by tahnik** [comment]
Thanks Ali, We will take each one of them into account.

**Comment by tahnik** [comment]
I am opening individual issues for them. We can't fix all of them before launch
